### ISSUE TITLE
[FEATURE][POSTURE] READ APPLICATION SERVICE 생성

### ISSUE THREAD

**Issue by jiwon11** [SpineTracker60/back-end#19]
## Description
자세 기록에 대한 READ APPLICATION SERVICE 생성

---

## TODO
- [x]  자세 기록에 대한 READ APPLICATION SERVICE 생성
- [x] 일간 총 시간
- [x] 일간 집중 시간
- [x] 일간 거북목 총 시간
- [x] 일간 비대칭 총 시간
- [ ] 일간 경고 횟수
- [x] 주간,월간 자세별 바른 자세 시간 추이

---

## ETC

---
* 없음
