### ISSUE TITLE
[REFACTORING][MEMBER] MEMBERINFO 엔티티 생성 및 CREATE APPLICATION SERVICE(MEMBERINFO) 구현

### ISSUE THREAD

**Issue by byallfine01** [SpineTracker60/back-end#36]
## Description
기존에 구현한 MEMBERINFOVO를 엔티티로 만들고, 직업, 성별, 생년월일 3개 모두 값이 있어야만 회원가입이 될 수 있게 로직 구현 예정

---

## TODO
- [x]  MEMBERINFO 엔티티 생성
- [x] CREATE APPLICATION SERVICE(MEMBERINFO) 구현
- [x] 테스트 코드 구현

---

## ETC

---
* 없음
