### ISSUE TITLE
[FEATURE][POSTURE] 오늘의 서머리 조회 Controller 구현

### ISSUE THREAD

**Issue by jiwon11** [SpineTracker60/back-end#59]
## Description
새로운 기능 추가에 관련 된 이슈 템플릿입니다.

---

## TODO
- [ ] 오늘의 서머리 조회 Controller 구현
- [ ] 일간 집중 시간
- [ ] 일간 불안정 자세 총 시간
- [ ] 일단 졸음 횟수
- [ ] 일간 경고 횟수
- [ ] 일간 자세별 지속 시간

---

## ETC

<img width="849" alt="CleanShot 2023-09-19 at 18 28 10@2x" src="https://github.com/SpineTracker60/back-end/assets/19159759/af8a15bd-7893-4d0d-8561-6a4c4b1ab5b9">

---
* 없음
