### ISSUE TITLE
[FEATURE][POSTURE] 대시보드 관련 Controller 구현

### ISSUE THREAD

**Issue by jiwon11** [SpineTracker60/back-end#60]
## Description
새로운 기능 추가에 관련 된 이슈 템플릿입니다.

---

## TODO
- [ ] 일간 자세별 시간
- [ ] 주간 평균 집중 시간 및 불안정 자세별 누적 시간
- [ ] 월간 평균 집중 시간 및 불안정 자세별 누적 시간
---

## ETC

<img width="897" alt="CleanShot 2023-09-19 at 18 27 48@2x" src="https://github.com/SpineTracker60/back-end/assets/19159759/0e1f89b5-7857-417d-87e9-c8cccf1c79cd">

---
* 없음
